/**
 * Information-question router.
 *
 * Handles the `route_question` policy decision for product-shaped
 * customer questions ("how much is the suspender?", "is it in stock?",
 * "what sizes does it come in?"). The customer-facing answer text is
 * generated by the composer override downstream — this handler's job
 * is to anchor the right product on commerceState so subsequent turns
 * (e.g. "yes pls", "I want the 2 years size") have a focus to attach
 * to via dialoguePolicy rule 1e and section 6/7.
 *
 * Architecture note: this handler does NOT promote a product into
 * pendingProductId. A price/stock/variant question is curiosity, not
 * commitment. The customer's next "yes pls" is what should promote a
 * mention into pending — and that path is already wired through
 * handleProductSelection (dialoguePolicy.ts:188-203). Setting
 * pendingProductId here would collapse the mention/commit distinction
 * the codebase intentionally maintains in
 * src/ai-v2/types.ts:138-141.
 */

import type { AiTurnResult, PersistedCommerceState, TurnContext } from '../types';
import type { QuestionIntent } from '../knowledge/types';
import { db } from '@/lib/firebase-admin';
import { FieldValue } from 'firebase-admin/firestore';
import {
  resolveInfoQuestionProductAnchor,
  type AnchorResult,
  type AnchorSource,
} from '../state/resolveInfoQuestionProductAnchor';
import { handleInformationQuestion } from './handleInformationQuestion';
import { buildStoreKnowledge } from '../knowledge/buildStoreKnowledge';
import { toKnowledgeTurnContext } from '../knowledge/adapters/fromTurnContext';

/**
 * Catch-fallback when the answer pipeline throws. Specific text per
 * Bundle A spec — never the old placeholder.
 */
const ANSWER_ERROR_FALLBACK =
  "Sorry please, I couldn't find that detail. Which product are you asking about?";

/**
 * Anchor sources that justify writing lastMentionedProductId.
 *
 *   explicit_name        — customer named a product the resolver
 *                          discovered. New association.
 *   displayed_products   — pronoun + recently shown. New association.
 *   cart_single_item     — gated to product-shaped intents in the
 *                          resolver, so the lone cart item is the
 *                          real referent of the question.
 *
 * Sources that do NOT trigger a write:
 *
 *   pending_product      — already in commerceState. No-op.
 *   last_mentioned       — already in commerceState. No-op.
 *   ambiguous            — multiple candidates. Refuse to guess.
 *   none                 — nothing to anchor.
 */
const ANCHOR_SOURCES_THAT_WRITE: ReadonlySet<AnchorSource> = new Set<AnchorSource>([
  'explicit_name',
  'displayed_products',
  'cart_single_item',
]);

/**
 * Local persistence helper. Mirrors the pattern in handleVariantReply,
 * handleProductSearch, and handleProductSelection. Each navigation
 * handler currently has its own copy — extraction to a shared module
 * is intentionally deferred (separate cleanup PR; see review notes).
 */
async function persistCommerceState(
  ctx: TurnContext,
  state: PersistedCommerceState,
): Promise<void> {
  const convRef = db
    .collection('stores')
    .doc(ctx.storeId)
    .collection('ai_conversations')
    .doc(ctx.conversationId);

  await convRef.set(
    {
      commerceState: state,
      updatedAt: FieldValue.serverTimestamp(),
    },
    { merge: true },
  );
}

/**
 * Build the debug.reason string per the agreed format:
 *
 *   info_question_anchor:{source}:{productId}
 *   info_question_anchor:ambiguous
 *   info_question_anchor:none
 */
function buildAnchorReason(anchor: AnchorResult): string {
  if (anchor.source === 'ambiguous' || anchor.source === 'none') {
    return `info_question_anchor:${anchor.source}`;
  }
  return `info_question_anchor:${anchor.source}:${anchor.productId}`;
}

export async function handleInformationQuestionRouter(
  ctx: TurnContext,
  questionIntent: QuestionIntent,
): Promise<AiTurnResult> {
  const stateBefore = ctx.commerceState.state;
  const anchor = resolveInfoQuestionProductAnchor(ctx, questionIntent);

  // Persist only when the resolver surfaced a NEW association the
  // state doesn't already reflect. No state transition; we preserve
  // every other field of commerceState (state name, stateEnteredAt,
  // expiresAt, pendingProductId, pendingVariantId,
  // lastShownProductIds, etc.) and update only lastMentionedProductId.
  //
  // The third condition (lastMentionedProductId !== productId) skips
  // the Firestore write when the value is already what we'd write —
  // saves a round-trip on repeated questions about the same product.
  if (
    anchor.productId &&
    ANCHOR_SOURCES_THAT_WRITE.has(anchor.source) &&
    ctx.commerceState.lastMentionedProductId !== anchor.productId
  ) {
    const newState: PersistedCommerceState = {
      ...ctx.commerceState,
      lastMentionedProductId: anchor.productId,
    };
    await persistCommerceState(ctx, newState);
    // Mirror the resolved anchor in memory so the answer pipeline below
    // sees the new product on this same turn. Without this, the explicit
    // anchor only takes effect on the NEXT turn (the persist hits
    // Firestore but ctx.commerceState is the snapshot loaded at the
    // start of this turn).
    ctx.commerceState.lastMentionedProductId = anchor.productId;
  }

  // Build the deterministic answer using the existing knowledge layer.
  // Pure orchestration: handleInformationQuestion does NOT mutate
  // commerce state. State stays at stateBefore for info questions.
  let composedReply: string;
  let answerTelemetry: string;
  try {
    const knowledgeCtx = toKnowledgeTurnContext(ctx);
    const knowledge = buildStoreKnowledge(ctx.storeData, knowledgeCtx.deliveryZones);
    const result = handleInformationQuestion(questionIntent, knowledgeCtx, knowledge);
    composedReply = result.composedReply;
    answerTelemetry = `info_answer:${questionIntent}:${result.telemetry.answerSource}`;
  } catch (err) {
    console.error('[handleInformationQuestionRouter] answer pipeline failed:', err);
    composedReply = ANSWER_ERROR_FALLBACK;
    answerTelemetry = `info_answer_error:${questionIntent}`;
  }

  return {
    reply: { type: 'text', content: composedReply },
    debug: {
      stateBefore,
      stateAfter: stateBefore,
      handler: 'handleInformationQuestionRouter',
      reason: `${buildAnchorReason(anchor)}|${answerTelemetry}`,
    },
  };
}